# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - extra-azure-devops-variables/*


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TfxInstaller@2
  inputs:
    version: 'v0.6.x'

- task: QueryAzureDevOpsExtensionVersion@2
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Marketplace'
    publisherId: 'FlorisDevreese'
    extensionId: 'pipeline-naming'
    versionAction: 'Patch'
    setBuildNumber: 'true'
    cwd: 'pipeline-naming'