trigger:
  paths:
    include:
    - extra-azure-devops-variables/*
    exclude:
    - extra-azure-devops-variables/test/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  workFolder: extra-azure-devops-variables/calculate-extra-azure-devops-variables

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(workFolder)'
    
- task: PowerShell@2
  displayName: Compile TypeScript
  inputs:
    targetType: 'inline'
    script: 'tsc'
    pwsh: true
    workingDirectory: '$(workFolder)'

- task: TfxInstaller@2
  inputs:
    version: 'v0.6.x'

- task: QueryAzureDevOpsExtensionVersion@2
  displayName: Increase extension version
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Marketplace'
    publisherId: 'FlorisDevreese'
    extensionId: extra-azure-devops-variables
    versionAction: 'Patch'
    setBuildNumber: 'true'
    cwd: 'extra-azure-devops-variables'

- task: PackageAzureDevOpsExtension@2
  displayName: Package extension
  inputs:
    rootFolder: 'extra-azure-devops-variables'
    localizationRoot: 'extra-azure-devops-variables'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true
    updateTasksVersionType: 'patch'

- task: PublishAzureDevOpsExtension@2
  displayName: Publish extension
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Marketplace'
    fileType: 'vsix'
    vsixFile: '*.vsix'

# - task: IsAzureDevOpsExtensionValidServer@2
#   inputs:
#     connectTo: 'VsTeam'
#     connectedServiceName: 'Marketplace'
#     method: 'id'
#     publisherId: 'FlorisDevreese'
#     extensionId: 'extra-azure-devops-variables'

# other build tasks see: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks&targetId=e59fd111-3faf-4b90-be81-9def48f2947b&utm_source=vstsproduct&utm_medium=ExtHubManageList